sudo: false
language: java

services:
  - docker

before_install:
  - mkdir -p output

  - docker pull asciidoctor/docker-asciidoctor

script:
    - chmod +x mvnw
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    mvn clean verify
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name readme-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name readme-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc

  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name doc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output doc/*.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name doc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output doc/*.adoc


after_failure:
  - docker logs readme-to-html
  - docker logs readme-to-pdf
  - docker logs doc-to-html
  - docker logs doc-to-pdf


after_success:
  - cd output ; mv README.html index.html ; cp -R ../doc doc
  - git init
  - git config --global  user.name "${GH_USER_NAME}"
  - git config --global  user.email "{GH_USER_EMAIL}"
  - git status
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git checkout -b gh-pages
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" gh-pages
